return {
  -- {
  --   'pmizio/typescript-tools.nvim',
  --   dependencies = { 'nvim-lua/plenary.nvim', 'neovim/nvim-lspconfig' },
  --   config = function()
  --     -- local mason_registry = require 'mason-registry'
  --     -- local vue_language_server_path = mason_registry.get_package('vue-language-server'):get_install_path() .. '/node_modules/@vue/language-server'
  --
  --     require('typescript-tools').setup {
  --       filetypes = {
  --         'javascript',
  --         'javascriptreact',
  --         'typescript',
  --         'typescriptreact',
  --
  --         'vue', -- This needed to be added.
  --       },
  --       settings = {
  --         expose_as_code_action = { 'add_missing_imports', 'remove_unused' },
  --
  --         tsserver_plugins = {
  --           -- Seemingly this is enough, no name, location or languages needed.
  --           '@vue/typescript-plugin',
  --         },
  --       },
  --     }
  --     require('lspconfig').volar.setup {}
  --   end,
  -- },
}
